/* products.js — demo product catalog (small sample) */
const PRODUCTS = [
  {
    id: "p001",
    title: "Wireless Noise-Cancelling Headphones",
    price: 119.99,
    oldPrice: 159.99,
    rating: 4.6,
    reviews: 3210,
    category: "Electronics",
    image: "https://via.placeholder.com/420x300?text=Headphones",
    badge: "Hot",
    offer: true,
    description: "Crisp audio, long battery life and premium comfort."
  },
  {
    id: "p002",
    title: "Smartwatch with Heart Rate Monitor",
    price: 89.99,
    oldPrice: 129.99,
    rating: 4.3,
    reviews: 845,
    category: "Electronics",
    image: "https://via.placeholder.com/420x300?text=Smartwatch",
    badge: "Deal",
    offer: true,
    description: "Fitness tracking, notifications and extended battery."
  },
  {
    id: "p003",
    title: "Men's Casual Sneakers",
    price: 49.99,
    oldPrice: 79.99,
    rating: 4.1,
    reviews: 540,
    category: "Fashion",
    image: "https://via.placeholder.com/420x300?text=Sneakers",
    badge: "Trending",
    offer: false,
    description: "Comfortable all-day wear with breathable fabric."
  },
  {
    id: "p004",
    title: "Women's Summer Dress",
    price: 39.99,
    oldPrice: null,
    rating: 4.5,
    reviews: 1200,
    category: "Fashion",
    image: "https://via.placeholder.com/420x300?text=Dress",
    badge: "New",
    offer: false,
    description: "Lightweight dress, great for beach or casual outings."
  },
  {
    id: "p005",
    title: "Blender & Smoothie Maker",
    price: 59.99,
    oldPrice: 89.99,
    rating: 4.2,
    reviews: 210,
    category: "Home",
    image: "https://via.placeholder.com/420x300?text=Blender",
    badge: "",
    offer: true,
    description: "Powerful motor, easy clean and multiple speed settings."
  },
  {
    id: "p006",
    title: "LED Desk Lamp with USB",
    price: 24.99,
    oldPrice: 34.99,
    rating: 4.0,
    reviews: 98,
    category: "Home",
    image: "https://via.placeholder.com/420x300?text=Desk+Lamp",
    badge: "",
    offer: false,
    description: "Adjustable brightness and color temperature."
  },
  {
    id: "p007",
    title: "Organic Face Moisturizer",
    price: 18.99,
    oldPrice: null,
    rating: 4.7,
    reviews: 430,
    category: "Beauty",
    image: "https://via.placeholder.com/420x300?text=Moisturizer",
    badge: "Best Seller",
    offer: true,
    description: "Light formula with natural ingredients for daily hydration."
  },
  {
    id: "p008",
    title: "Bluetooth Portable Speaker",
    price: 39.99,
    oldPrice: 59.99,
    rating: 4.4,
    reviews: 721,
    category: "Electronics",
    image: "https://via.placeholder.com/420x300?text=Speaker",
    badge: "",
    offer: true,
    description: "Small, water-resistant speaker with punchy bass."
  },
  {
    id: "p009",
    title: "Kids' Educational Toy Set",
    price: 29.99,
    oldPrice: 39.99,
    rating: 4.3,
    reviews: 150,
    category: "Toys",
    image: "https://via.placeholder.com/420x300?text=Toy+Set",
    badge: "Kids",
    offer: false,
    description: "Stimulating set for ages 3+, fosters creativity and learning."
  },
  {
    id: "p010",
    title: "Ergonomic Office Chair",
    price: 199.99,
    oldPrice: 269.99,
    rating: 4.5,
    reviews: 410,
    category: "Furniture",
    image: "https://via.placeholder.com/420x300?text=Office+Chair",
    badge: "",
    offer: true,
    description: "Lumbar support, adjustable height and breathable mesh."
  },
  {
    id: "p011",
    title: "Classic Sunglasses (Unisex)",
    price: 29.99,
    oldPrice: null,
    rating: 4.0,
    reviews: 88,
    category: "Fashion",
    image: "https://via.placeholder.com/420x300?text=Sunglasses",
    badge: "",
    offer: false,
    description: "UV protection with a timeless frame."
  },
  {
    id: "p012",
    title: "Stainless Steel Water Bottle",
    price: 19.99,
    oldPrice: 24.99,
    rating: 4.4,
    reviews: 631,
    category: "Home",
    image: "https://via.placeholder.com/420x300?text=Water+Bottle",
    badge: "",
    offer: true,
    description: "Keeps beverages hot or cold for hours."
  }
];